name: "node_docker_project"

services:
  mongodb:
    image: mongo
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  backend:
    depends_on:
      - mongodb
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - MONGO_URI=$MONGO_URI
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
      - ./backend/upload:/backend/upload

volumes:
  db: